### ISSUE TITLE
SSP server error

### ISSUE THREAD

**Issue by Petrol12** [ZelGimi/supersolarpanels#12]
Hello, when starting the minecraft server 1.12.2 on the Mohist core, errors related to running or jumping appear:
****
[17:48:54 ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingJumpEvent@5e1421eb:
 java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.denfop.ssp.events.EventHandler.jump(EventHandler.java:101) ~[EventHandler.class:1.4.0]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_139_EventHandler_jump_LivingJumpEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:485) ~[ForgeHooks.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70664_aZ(EntityLivingBase.java:2102) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70664_aZ(EntityPlayer.java:1955) ~[aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:769) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) ~[lk$a.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[17:48:54 ERROR]: Index: 2 Listeners:
[17:48:54 ERROR]: 0: NORMAL
[17:48:54 ERROR]: 1: ASM: class thaumcraft.common.lib.events.PlayerEvents playerJumps(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingJumpEvent;)V
[17:48:54 ERROR]: 2: ASM: com.denfop.ssp.events.EventHandler@14747d94 jump(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingJumpEvent;)V
[17:48:54 FATAL]: Error executing task
****
All this continues until it stops running around the world

list of mods:
Thaumcraft_1.12.2_6.1.BETA26
Baubles-1.12-1.5.2
industrialcraft-2-2.8.221-ex112
SuperSolarPanels-1.12.2-1.4.0 FIX
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
theoneprobe-1.12-1.4.28
jei_1.12.2-4.16.1.302

**Comment by Tassadar0** [comment]
I only added IC2 and this module also got this error

**Comment by Moyurei** [comment]
Same problem came in my server as well.
After assembled a test server with only ic2 and sspr(ver.1.4.0), I found this problem occured every time a player was jumping(not sure that jumping is the only trigger). Tested with different server cores(mohist and sponge) and problem both appeared.
It will be appreciated much if such problem could be fixed. : )

**Comment by ZelGimi** [comment]
Thanks for  bug. This bug will be fix in the next update.

**Comment by ZelGimi** [comment]
Solved
